authentication-lb:
  scale: 2
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: http
      service:  authentication_ms/authentication_ms
      source_port: 80
      target_port: 4000
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
    interval: 2000